import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import pluginVue from 'eslint-plugin-vue'

export default tseslint.config(
  {
    ignores: [
      'dist/**', 'node_modules/**', 'assets/vendor/**', 'docs/**', 'test-results/**',
      // services/*.d.ts 是 build:runtime 生成产物，不参与 lint
      'services/*.d.ts', 'services/*.js',
      'scripts/archive/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  {
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
        sourceType: 'module',
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        alert: 'readonly',
        structuredClone: 'readonly',
        TextDecoder: 'readonly',
        DataView: 'readonly',
        Uint8Array: 'readonly',
        ArrayBuffer: 'readonly',
        Intl: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        globalThis: 'readonly',
        indexedDB: 'readonly',
        IDBDatabase: 'readonly',
        IDBTransaction: 'readonly',
        IDBRequest: 'readonly',
        createImageBitmap: 'readonly',
        SpeechSynthesis: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        HTMLDialogElement: 'readonly',
      },
    },
    rules: {
      // 个人项目门禁：未使用变量、显式 any 回退、console 残留、v-html XSS
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        // TS 类型导入（import type / type 修饰符）不应报未使用
        caughtErrors: 'none',
      }],
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'vue/no-v-html': 'warn',
      // 模板纯风格规则关闭：项目有自己的一致性，不按 eslint 默认模板风格排版
      'vue/multi-word-component-names': 'off',
      'vue/attributes-order': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/html-self-closing': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-indent': 'off',
      'vue/html-quotes': 'off',
      'vue/first-attribute-linebreak': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/component-definition-name-casing': 'off',
      'vue/require-default-prop': 'off',
      // 正确性规则（2026-08-22 恢复）：v-for 无 key 会导致列表复用错乱；
      // 子组件变更 props 会破坏单向数据流。其余纯风格规则继续豁免。
      'vue/require-v-for-key': 'error',
      'vue/no-mutating-props': 'error',
      'vue/no-v-model-argument': 'off',
      'vue/v-on-event-hyphenation': 'off',
      'vue/attribute-hyphenation': 'off',
      'vue/html-button-has-type': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/html-closing-bracket-spacing': 'off',
      'vue/valid-v-model': 'off',
      'vue/no-unused-refs': 'off',
      'vue/valid-template-root': 'off',
      'vue/no-template-shadow': 'off',
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-empty': 'off',
      'no-useless-escape': 'off',
      'no-constant-condition': 'off',
      'no-control-regex': 'off',
      'no-prototype-builtins': 'off',
      'no-case-declarations': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // 历史 services 代码的既有模式（this 别名、namespace、Function 类型），
      // 重构时随文件一起治理，不在本次门禁里硬卡
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      'no-useless-assignment': 'off',
      'no-unassigned-vars': 'off',
      'prefer-const': 'off',
      'preserve-caught-error': 'off',
    },
  },
  {
    files: ['**/*.vue'],
    rules: {
      'vue/component-definition-name-casing': 'off',
      // .vue 模板消费的脚本导入 ESLint 不可见，未使用判断交给 vue-tsc
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    // 维护/测试脚本：console 是 CLI 输出方式，不按应用代码的 no-console 管
    files: ['scripts/**', 'routes/**'],
    rules: {
      'no-console': 'off',
    },
  },
)
