import type { ArtistStyleOption } from './artistStyles.ts'

// 官方原画师收录区段（2026-09-05 从 artistStyleCatalog.ts 抽出：单体门禁 625>600 拆分）。
// 明日方舟官方画师（2026-08-31 调研收录）+ 巨人/我推/终末地官方阵容（5582f9d6）。
export const ARTIST_STYLE_OFFICIAL_OPTIONS: readonly ArtistStyleOption[] = Object.freeze([
  // ── 明日方舟官方画师（2026-08-31 调研收录，Danbooru 主 tag 已核实）─────
  {
    id: 'xiayehongming',
    name: 'Xiaye Hongming',
    cnName: '下野宏銘',
    waiTag: 'xiayehongming',
    animaTag: '@xiayehongming',
    description: '《明日方舟》令/温蒂/琴柳原案、无轮廓色块拼接与东方古典气韵',
    masterpiece: '《明日方舟》（令、温蒂、琴柳、诗怀雅等数十位干员与大量皮肤）',
    category: 'grand',
    verification: 'curated',
    keywords: ['明日方舟', '令', '温蒂', '琴柳', '色块', '东方古典', '高对比', '方遒卷'],
  },
  {
    id: 'huanxiang_heitu',
    name: 'Huanxiang Heitu',
    cnName: '幻象黑兔',
    waiTag: 'huanxiang_heitu',
    animaTag: '@huanxiang heitu',
    description: '《明日方舟》夕/能天使原案、神魔幻想华美与精致装饰细节',
    masterpiece: '《明日方舟》（夕、能天使）、《少女前线》画师',
    category: 'grand',
    verification: 'curated',
    keywords: ['明日方舟', '夕', '能天使', '幻想', '华美', '神魔', '装饰'],
  },
  {
    id: 'liduke',
    name: 'Liduke',
    cnName: '小日子',
    waiTag: 'liduke',
    animaTag: '@liduke',
    description: '《明日方舟》森蚺/波登可原案、柔和半厚涂与细腻温暖光感',
    masterpiece: '《明日方舟》（森蚺、波登可）',
    category: 'grand',
    verification: 'curated',
    keywords: ['明日方舟', '森蚺', '波登可', '厚涂', '柔和', '治愈'],
  },
  {
    id: 'alchemaniac',
    name: 'alchemaniac',
    cnName: 'alchemaniac',
    waiTag: 'alchemaniac',
    animaTag: '@alchemaniac',
    description: '《明日方舟》斯卡蒂原案、冷调忧郁氛围与深海主题',
    masterpiece: '《明日方舟》（斯卡蒂）',
    category: 'cinematic',
    verification: 'curated',
    keywords: ['明日方舟', '斯卡蒂', '冷色调', '忧郁', '海洋', '氛围'],
  },
  {
    id: 'asano_kyoji',
    name: 'Asano Kyoji',
    cnName: '浅野恭司',
    waiTag: 'asano_kyoji',
    animaTag: '@asano kyoji',
    description: '《进击的巨人》第1-3季总作监与角色设计、标志性深黑重轮廓线与强动态张力',
    masterpiece: '《进击的巨人》第1-3季动画角色设计与总作画监督、《PSYCHO-PASS 心理测量者》',
    category: 'grand',
    verification: 'curated',
    keywords: ['进击的巨人', '三笠', '艾伦', '兵长', '利威尔', '总作监', 'wit studio', '霸权社', '硬朗线条'],
  },
  {
    id: 'isayama_hajime',
    name: 'Isayama Hajime',
    cnName: '谏山创',
    waiTag: 'isayama_hajime',
    animaTag: '@isayama hajime',
    description: '《进击的巨人》漫画原作者、深刻情感张力与史诗级绝望与坚毅神态',
    masterpiece: '《进击的巨人》（Attack on Titan）原作漫画',
    category: 'grand',
    verification: 'curated',
    keywords: ['进击的巨人', '谏山创', '原作', '漫画', '绝望感', '史诗感', '眼神张力'],
  },
  {
    id: 'yokoyari_mengo',
    name: 'Yokoyari Mengo',
    cnName: '横枪萌果',
    waiTag: 'yokoyari_mengo',
    animaTag: '@yokoyari mengo',
    description: '《我推的孩子》漫画作画、水润晶莹星眸与细腻情绪表现力',
    masterpiece: '《【我推的孩子】》（Oshi no Ko）漫画作画、《人渣的本愿》原作',
    category: 'pure',
    verification: 'curated',
    keywords: ['我推的孩子', '星野爱', '黑川茜', '有马加奈', '星星眼', '横枪', '水润', '细腻'],
  },
  {
    id: 'wei_at_w',
    name: 'Wei@W',
    cnName: '唯@W',
    waiTag: 'wei_at_w',
    animaTag: '@wei at w',
    description: '《明日方舟》主美与核心角色设计、机能机甲概念与利落冷艳气质',
    masterpiece: '《明日方舟》（阿米娅、陈、佩丽卡等核心角色设计与世界观视觉监修）',
    category: 'cinematic',
    verification: 'curated',
    keywords: ['明日方舟', '终末地', '唯@W', '主美', '机能风', '佩丽卡', '伊冯', '概念设计'],
  },
])
